# Cadastro automático de itens da tabela

### Este programa irá pegar dados da tabela carros_dados e cadastrar no carros_artigo exe

Programa desenvolvido por Ruan José

In [1]:
import pyautogui
import time
import pandas as pd

In [2]:
#importando a base de dados 

tabela = pd.read_csv("Carros.csv")
display(tabela)

     CHASSI                             NOMECARRO  KMPORDIA COMBUSTIVEL
0      1023                        Toyota Corolla        41      diesel
1      1079                           Honda Civic        28    gasolina
2      1182                          Ford Mustang        24      diesel
3      1288                      Chevrolet Camaro        59    gasolina
4      1329                       Volkswagen Golf        50      diesel
..      ...                                   ...       ...         ...
595   30398                  Hyundai i20 N Line S        90    Gasolina
596   30444                     Kia Rio GT-Line S        61      Álcool
597   30488  Nissan Micra N-Sport Limited Edition        52      Diesel
598   30533                 Toyota Yaris GR Sport        37         GNV
599   30578                           Honda HR-V         74    Gasolina

[600 rows x 4 columns]

In [3]:
#tirar as colunas desnecessarias
tabela = tabela.drop(columns="CHASSI")
tabela = tabela.drop(columns="NOMECARRO")
display(tabela)

     KMPORDIA COMBUSTIVEL
0          41      diesel
1          28    gasolina
2          24      diesel
3          59    gasolina
4          50      diesel
..        ...         ...
595        90    Gasolina
596        61      Álcool
597        52      Diesel
598        37         GNV
599        74    Gasolina

[600 rows x 2 columns]

In [4]:
# corrigir o que tiver de errado c a base de dados
display(tabela.info())
# se tivessem valores vazios - excluir as linhas que têm valores vazios
tabela = tabela.dropna()

display(tabela.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   KMPORDIA     600 non-null    int64
 1   COMBUSTIVEL  600 non-null    object
dtypes: int64(1), object(1)
memory usage: 9.5+ KB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   KMPORDIA     600 non-null    int64
 1   COMBUSTIVEL  600 non-null    object
dtypes: int64(1), object(1)
memory usage: 9.5+ KB

None

In [5]:
qnt_de_linhas = tabela["COMBUSTIVEL"].count()
xint = int(qnt_de_linhas)

'''# pegar da tabela o valor do campo que a gente quer preencher
km = tabela.loc[linha, "codigo"]
# preencher o campo
pyautogui.write(str(codigo))
# passar para o proximo campo
pyautogui.press("tab")

pyautogui.write(str(tabela.loc[linha, "marca"]))
pyautogui.press("tab")'''

'# pegar da tabela o valor do campo que a gente quer preencher\nkm = tabela.loc[linha, "codigo"]\n# preencher o campo\npyautogui.write(str(codigo))\n# passar para o proximo campo\npyautogui.press("tab")\n\npyautogui.write(str(tabela.loc[linha, "marca"]))\npyautogui.press("tab")'

In [6]:
# da ao python os valores p entrar no programa
mapeamento = {
    'gasolina': 1,
    'alcool': 2,
    'diesel': 3,
    'gnv':4,
    'Gasolina': 1,
    'Álcool': 2,
    'Diesel': 3,
    'GNV': 4,
}

tabela['COMBUSTIVEL'] = tabela['COMBUSTIVEL'].replace(mapeamento)
display(tabela)

C:\Users\Ruanj\AppData\Local\Temp\ipykernel_2116\2939227518.py:13: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  tabela['COMBUSTIVEL'] = tabela['COMBUSTIVEL'].replace(mapeamento)

     KMPORDIA  COMBUSTIVEL
0          41            3
1          28            1
2          24            3
3          59            1
4          50            3
..        ...          ...
595        90            1
596        61            2
597        52            3
598        37            4
599        74            1

[600 rows x 2 columns]

In [7]:
#abrir o programa carro_artigo.exe
pyautogui.PAUSE = 0.6

pyautogui.press("win")
pyautogui.write("vscode")
pyautogui.press("enter")
time.sleep(5)

pyautogui.hotkey('ctrl', 'k', 'o')
pyautogui.write(r"C:\Users\Ruanj\Documents\TRANSVERSAL")
pyautogui.press("enter")
pyautogui.press("enter")
pyautogui.press("f11")

pyautogui.press("f6")
time.sleep(5)

pyautogui.typewrite("s")
pyautogui.press("enter")

pyautogui.write(str(xint))
pyautogui.press("enter")
time.sleep(2)

for linha in tabela.index:
    pyautogui.PAUSE = 0.2
    #digita os km
    pyautogui.write(str(tabela.loc[linha, "KMPORDIA"]))
    pyautogui.press("enter")

time.sleep(2)

for linha in tabela.index:
    pyautogui.PAUSE = 0.2
    #digita os km
    pyautogui.write(str(tabela.loc[linha, "COMBUSTIVEL"]))
    pyautogui.press("enter")

pyautogui.write(str(xint))
pyautogui.press("enter")

FailSafeException: PyAutoGUI fail-safe triggered from mouse moving to a corner of the screen. To disable this fail-safe, set pyautogui.FAILSAFE to False. DISABLING FAIL-SAFE IS NOT RECOMMENDED.